// Mocks generated by Mockito 5.4.6 from annotations
// in clean_sample/test/features/auth/domain/usecases/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:clean_sample/core/utils/result/result.dart' as _i4;
import 'package:clean_sample/features/auth/domain/entities/app_user/app_user.dart'
    as _i5;
import 'package:clean_sample/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.AppUser>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.Result<_i5.AppUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AppUser>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AppUser>>);

  @override
  _i3.Future<_i4.Result<_i5.AppUser>> signup(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [email, password]),
            returnValue: _i3.Future<_i4.Result<_i5.AppUser>>.value(
              _i6.dummyValue<_i4.Result<_i5.AppUser>>(
                this,
                Invocation.method(#signup, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AppUser>>);
}
